version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Porta para conexões AMQP
      - "15672:15672" # Porta para o painel de gerenciamento web
    environment:
      RABBITMQ_DEFAULT_USER: guest # Usuário padrão
      RABBITMQ_DEFAULT_PASS: guest # Senha padrão
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persistência de dados

volumes:
  rabbitmq_data:
